#!/bin/bash

pushd "$2" > /dev/null || exit
git_uid="$(ls -nd .git | awk '{print $3}')"
git_usr="$(ls -ld .git | awk '{print $3}')"
popd > /dev/null || exit

if [ "$(id -u)" != "${git_uid}" ]
then
  echo "FORCING CORRECT USER ${git_usr} (${git_uid})"
  sudo su "${git_usr}" -s /bin/bash -c "$0 $*"
  exit $?
fi



if [ "$1" = "force" ]; then

  pushd "$2" > /dev/null || exit
  git fetch
  git reset origin --hard
  popd > /dev/null || exit

elif [ "$1" = "normal" ]; then

  pushd "$2" > /dev/null || exit
  git pull
  popd > /dev/null || exit

elif [ "$1" = "push" ]; then

  pushd "$2" > /dev/null || exit
  git push
  popd > /dev/null || exit

elif [ "$1" = "forcepush" ]; then

  pushd "$2" > /dev/null || exit
  git push --force
  popd > /dev/null || exit

elif [ "$1" = "status" ]; then

  pushd "$2" > /dev/null || exit
  git status
  popd > /dev/null || exit

fi
